--- 
- name: installing jdk
  hosts: localhost
  become: yes
  tasks:
    - name: installing jdk
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
